### ISSUE TITLE
Need an exchange page to display crypto prices using Coingecko API 

### ISSUE THREAD

**Issue by Octet3290** [Octet3290/octypto#1]

**Comment by issa-me-sush** [comment]
hey! I would love to work on this, could you let me know few things- should we make a new route  where  the exchange page is  present ? or extend the single page? also what  tokens/crypto's prices do we need to display? is it just a display  of latest prices?
Have previously worked with coingecko api, this would be interesting  to work on , thank you :D

**Comment by Octet3290** [comment]
> hey! I would love to work on this, could you let me know few things- should we make a new route where the exchange page is present ? or extend the single page? also what tokens/crypto's prices do we need to display? is it just a display of latest prices? Have previously worked with coingecko api, this would be interesting to work on , thank you :D

Hey thanks for showing your interest in the octypto project. New route for exchange page will be appreciable. Top 20-30 tokens will be enough its totally up to you :) and coming up to the displaying, if you would be able to show the pump or dump percentage will be good.
