### ISSUE TITLE
Coin listing page required using API

### ISSUE THREAD

**Issue by Octet3290** [Octet3290/octypto#2]

**Comment by zainbinfurqan** [comment]
@Octet3290 Hi, i want to work on this issue can you please assign it to me?

**Comment by Octet3290** [comment]
> @Octet3290 Hi, i want to work on this issue can you please assign it to me?

go ahead :)

**Comment by zainbinfurqan** [comment]
@Octet3290  can you please provide some more details about issue?

**Comment by Octet3290** [comment]
> @Octet3290 can you please provide some more details about issue?

The coin listing page should show the current prices for the top 20 or top 30 crypto coins with the 24h change in their prices in percentage, rank, market cap etc. 
And if possible, upon clicking it should show the graph of the prices of respective coins.

**Comment by zainbinfurqan** [comment]
@Octet3290  got it. also, can you please guide how i can run the project locally, done for the client react app but little confused on smart_contract

**Comment by Octet3290** [comment]
> @Octet3290  got it. also, can you please guide how i can run the project locally, done for the client react app but little confused on smart_contract

Go to client directory and run "npm run dev" to run it locally on your system. Let me know if you have any other doubts :)

**Comment by zainbinfurqan** [comment]
@Octet3290  yeah i already did that but on connect wallet it showing me http://localhost:5173/ Please install metamask

**Comment by Octet3290** [comment]
> @Octet3290 yeah i already did that but on connect wallet it showing me http://localhost:5173/ Please install metamask

you have metamask installed ?

**Comment by zainbinfurqan** [comment]
@Octet3290  yes i did chorme extension for metamask

**Comment by Octet3290** [comment]
> @Octet3290  yes i did chorme extension for metamask
> 
> 

Which test network you are using ?

**Comment by zainbinfurqan** [comment]
@Octet3290  not sure about this, this is my first time to contribute in any web3 project, can you guide which network should i use?

**Comment by Octet3290** [comment]
> @Octet3290  not sure about this, this is my first time to contribute in any web3 project, can you guide which network should i use?

You can go for goerli test network
